### ISSUE TITLE
Link in readme page is expired

### ISSUE THREAD

**Issue by akucharcz** [acoustic-content-samples/wchtools-cli#59]
https://console.bluemix.net/docs/iam/userid_keys.html#userapikey seems to be expired
![image](https://user-images.githubusercontent.com/19893757/93587853-d0240700-f9aa-11ea-9da3-11e9190732df.png)

**Comment by mburati** [comment]
@akucharcz  - if you're an Acoustic customer, I believe that you should have received email about switching from IBM id to Acoustic id coming up soon.  As part of that change, you would also need to use Acoustic api keys (if you desire to use api key with wchtools instead of username / password pair) instead of IBM id based api keys as that prior document referred to.
The Acoustic id api keys are not live today, before the switch to the Acoustic ids,  but when that change is made, the following document should explain to you how to create an Acoustic api key for use with wchtools and/or calling the Acoustic Content login API yourself directly, from client code.  

https://help.goacoustic.com/hc/en-us/articles/360041347794

I hope that helps, and when that switch is made, we will update the readme with this information also.

..Mike (fyi @paugumienna @dkowcun ).

**Comment by mburati** [comment]
@will-izard-ac @paugumienna  - if you are done with updating the readme for this issue, could you please mark it complete?  Thanks.

**Comment by mburati** [comment]
@will-izard-ac @paugumienna @lukasz-reszka - if you are done with updating the readme for this issue, could you please mark it complete? Thanks.

**Comment by lukasz-reszka** [comment]
README.me updated with Acoustic API key, closing
